import type { BonCommande } from '@/types'

export const bonsCommande: BonCommande[] = [
  { id: 'bc01', numero: 'BC-2024-001', fournisseurId: 'f5', fournisseurNom: 'Excavations Fortier', projetId: 'p1', projetNom: 'Réfection infrastructures routières — Aylmer', statut: 'ferme', montantTotal: 128000, dateCreation: '2024-03-05', dateReception: '2024-03-18', notes: 'Excavation complète tronçon 1 et 2', items: [{ id: 'i1', description: 'Excavation et transport déblais', quantite: 4200, unite: 'm³', prixUnitaire: 28 }, { id: 'i2', description: 'Remblayage sélectif', quantite: 2800, unite: 'm³', prixUnitaire: 11.43 }] },
  { id: 'bc02', numero: 'BC-2024-002', fournisseurId: 'f1', fournisseurNom: 'Béton Provincial Inc.', projetId: 'p1', projetNom: 'Réfection infrastructures routières — Aylmer', statut: 'ferme', montantTotal: 95000, dateCreation: '2024-04-01', dateReception: '2024-04-15', notes: 'Béton structure chaussée', items: [{ id: 'i1', description: 'Béton 35 MPa livré chantier', quantite: 380, unite: 'm³', prixUnitaire: 250 }] },
  { id: 'bc03', numero: 'BC-2024-003', fournisseurId: 'f2', fournisseurNom: 'Aciers de construction Demers', projetId: 'p2', projetNom: 'Agrandissement entrepôt — Phase 2', statut: 'recu', montantTotal: 148000, dateCreation: '2024-04-10', dateReception: '2024-05-02', notes: 'Structure acier complète', items: [{ id: 'i1', description: 'Poutrelles IPE 200', quantite: 85, unite: 'unité', prixUnitaire: 980 }, { id: 'i2', description: 'Colonnes HEB 200', quantite: 24, unite: 'unité', prixUnitaire: 1450 }, { id: 'i3', description: 'Boulonnerie et plaques', quantite: 1, unite: 'forfait', prixUnitaire: 18080 }] },
  { id: 'bc04', numero: 'BC-2024-004', fournisseurId: 'f9', fournisseurNom: 'Isolation Thermax', projetId: 'p2', projetNom: 'Agrandissement entrepôt — Phase 2', statut: 'approuve', montantTotal: 58000, dateCreation: '2024-05-15', notes: 'Toiture membrane TPO + isolation', items: [{ id: 'i1', description: 'Membrane TPO 60 mil', quantite: 1200, unite: 'm²', prixUnitaire: 32 }, { id: 'i2', description: 'Isolant rigide RSI-3.5', quantite: 1200, unite: 'm²', prixUnitaire: 16.33 }] },
  { id: 'bc05', numero: 'BC-2024-005', fournisseurId: 'f8', fournisseurNom: 'Location Équipements Bouchard', projetId: 'p1', projetNom: 'Réfection infrastructures routières — Aylmer', statut: 'ferme', montantTotal: 42000, dateCreation: '2024-03-01', dateReception: '2024-03-02', notes: 'Location excavatrice et compacteur', items: [{ id: 'i1', description: 'Excavatrice 30T — 8 sem.', quantite: 8, unite: 'semaine', prixUnitaire: 3800 }, { id: 'i2', description: 'Compacteur vibrant — 8 sem.', quantite: 8, unite: 'semaine', prixUnitaire: 1450 }] },
  { id: 'bc06', numero: 'BC-2024-006', fournisseurId: 'f3', fournisseurNom: 'Électrique Marchand & Frères', projetId: 'p4', projetNom: 'Maintenance préventive postes HQ', statut: 'envoye', montantTotal: 68000, dateCreation: '2024-05-05', notes: 'Fournitures électriques maintenance Q2', items: [{ id: 'i1', description: 'Disjoncteurs MT 24 kV', quantite: 12, unite: 'unité', prixUnitaire: 4200 }, { id: 'i2', description: 'Câbles HV 35 kV', quantite: 850, unite: 'm', prixUnitaire: 18 }, { id: 'i3', description: 'Accessoires et consommables', quantite: 1, unite: 'forfait', prixUnitaire: 12700 }] },
  { id: 'bc07', numero: 'BC-2024-007', fournisseurId: 'f5', fournisseurNom: 'Excavations Fortier', projetId: 'p6', projetNom: 'Réfection pont — rang du Sauvage', statut: 'ferme', montantTotal: 35000, dateCreation: '2024-04-15', dateReception: '2024-04-20', notes: 'Démontage tablier existant', items: [{ id: 'i1', description: 'Grue 80T — journée', quantite: 5, unite: 'jour', prixUnitaire: 7000 }] },
  { id: 'bc08', numero: 'BC-2024-008', fournisseurId: 'f12', fournisseurNom: 'Soudures Industrielles Gagné', projetId: 'p6', projetNom: 'Réfection pont — rang du Sauvage', statut: 'recu', montantTotal: 48000, dateCreation: '2024-05-01', dateReception: '2024-05-28', notes: 'Nouveau tablier acier galvanisé', items: [{ id: 'i1', description: 'Tablier acier 22m — fabrication + galva', quantite: 1, unite: 'forfait', prixUnitaire: 48000 }] },
  { id: 'bc09', numero: 'BC-2024-009', fournisseurId: 'f10', fournisseurNom: 'Peinture & Revêtements Lafond', projetId: 'p5', projetNom: 'Rénovation tour de bureaux — 12 étages', statut: 'brouillon', montantTotal: 85000, dateCreation: '2024-06-01', notes: 'Peinture tous étages — à confirmer', items: [{ id: 'i1', description: 'Peinture murs et plafonds', quantite: 14400, unite: 'm²', prixUnitaire: 5.9 }] },
  { id: 'bc10', numero: 'BC-2024-010', fournisseurId: 'f7', fournisseurNom: 'Menuiserie Pro Carpentier', projetId: 'p5', projetNom: 'Rénovation tour de bureaux — 12 étages', statut: 'brouillon', montantTotal: 62000, dateCreation: '2024-06-01', notes: 'Cloisons amovibles et portes', items: [{ id: 'i1', description: 'Cloisons amovibles modulaires', quantite: 48, unite: 'section', prixUnitaire: 950 }, { id: 'i2', description: 'Portes de bureau pleines', quantite: 48, unite: 'unité', prixUnitaire: 342 }] },
  { id: 'bc11', numero: 'BC-2024-011', fournisseurId: 'f1', fournisseurNom: 'Béton Provincial Inc.', projetId: 'p3', projetNom: 'Aqueduc — secteur Masson-Angers', statut: 'ferme', montantTotal: 72000, dateCreation: '2023-08-20', dateReception: '2023-08-25', notes: 'Béton enrobement tuyaux', items: [{ id: 'i1', description: 'Béton 20 MPa', quantite: 288, unite: 'm³', prixUnitaire: 250 }] },
  { id: 'bc12', numero: 'BC-2024-012', fournisseurId: 'f4', fournisseurNom: 'Plomberie Industrielle Savard', projetId: 'p4', projetNom: 'Maintenance préventive postes HQ', statut: 'approuve', montantTotal: 32000, dateCreation: '2024-05-10', notes: 'Plomberie locaux techniques', items: [{ id: 'i1', description: 'Tuyauterie acier inox DN50', quantite: 180, unite: 'm', prixUnitaire: 145 }, { id: 'i2', description: 'Raccords et vannes', quantite: 1, unite: 'forfait', prixUnitaire: 5900 }] },
]
