import type { Client } from '@/types'

export const clients: Client[] = [
  {
    id: 'c1',
    nom: 'Ville de Gatineau',
    type: 'public',
    secteur: 'municipal',
    adresse: '25 rue Laurier',
    ville: 'Gatineau',
    province: 'QC',
    codePostal: 'J8X 4C8',
    conditionsPaiement: 'Net 30',
    contacts: [
      { nom: 'Marie-Josée Langlois', poste: 'Directrice des travaux publics', email: 'mj.langlois@gatineau.ca', tel: '819-595-7777' },
      { nom: 'Patrice Gauthier', poste: 'Chargé de projets', email: 'p.gauthier@gatineau.ca', tel: '819-595-7788' },
    ],
    createdAt: '2022-03-15',
    projetsIds: ['p1', 'p3'],
    soumissionsIds: ['s1', 's5', 's12'],
    totalContrats: 3800000,
    tauxSucces: 42,
    margemoyenne: 11.2,
  },
  {
    id: 'c2',
    nom: 'Construction Gervais & Fils',
    type: 'prive',
    secteur: 'commercial',
    adresse: '4500 boul. St-Laurent',
    ville: 'Montréal',
    province: 'QC',
    codePostal: 'H2T 1R8',
    conditionsPaiement: 'Net 45',
    contacts: [
      { nom: 'Marc Gervais', poste: 'Président', email: 'm.gervais@gervaisconst.ca', tel: '514-555-0192' },
    ],
    createdAt: '2021-08-10',
    projetsIds: ['p2'],
    soumissionsIds: ['s2', 's8'],
    totalContrats: 1250000,
    tauxSucces: 55,
    margemoyenne: 14.5,
  },
  {
    id: 'c3',
    nom: 'Hydro-Québec',
    type: 'public',
    secteur: 'industriel',
    adresse: '75 boul. René-Lévesque Ouest',
    ville: 'Montréal',
    province: 'QC',
    codePostal: 'H2Z 1A4',
    conditionsPaiement: 'Net 60',
    contacts: [
      { nom: 'Sophie Tremblay', poste: 'Gestionnaire approvisionnement', email: 's.tremblay@hydroquebec.com', tel: '514-289-2211' },
      { nom: 'Jean-Paul Morin', poste: 'Directeur infrastructure', email: 'jp.morin@hydroquebec.com', tel: '514-289-3300' },
    ],
    createdAt: '2020-11-20',
    projetsIds: ['p4'],
    soumissionsIds: ['s3', 's9', 's15'],
    totalContrats: 6200000,
    tauxSucces: 35,
    margemoyenne: 9.8,
  },
  {
    id: 'c4',
    nom: 'Industries Lafarge Canada',
    type: 'prive',
    secteur: 'industriel',
    adresse: '1801 McGill College Ave',
    ville: 'Montréal',
    province: 'QC',
    codePostal: 'H3A 2N4',
    conditionsPaiement: 'Net 30',
    contacts: [
      { nom: 'Pierre Dubois', poste: 'VP Opérations', email: 'p.dubois@lafarge.com', tel: '514-861-1411' },
    ],
    createdAt: '2021-05-03',
    projetsIds: ['p5'],
    soumissionsIds: ['s4', 's10'],
    totalContrats: 2100000,
    tauxSucces: 50,
    margemoyenne: 13.1,
  },
  {
    id: 'c5',
    nom: 'Municipalité de Pontiac',
    type: 'public',
    secteur: 'municipal',
    adresse: '2024 route 148',
    ville: 'Pontiac',
    province: 'QC',
    codePostal: 'J0X 2G0',
    conditionsPaiement: 'Net 30',
    contacts: [
      { nom: 'Alain Chartrand', poste: 'Directeur général', email: 'a.chartrand@municipalitepontiac.ca', tel: '819-455-2401' },
    ],
    createdAt: '2022-07-18',
    projetsIds: ['p6'],
    soumissionsIds: ['s6', 's11'],
    totalContrats: 890000,
    tauxSucces: 60,
    margemoyenne: 12.0,
  },
  {
    id: 'c6',
    nom: 'CHSLD Perley-Rideau',
    type: 'public',
    secteur: 'institutionnel',
    adresse: '1750 Russell Rd',
    ville: 'Ottawa',
    province: 'ON',
    codePostal: 'K1G 5Z6',
    conditionsPaiement: 'Net 45',
    contacts: [
      { nom: 'Nathalie Bergeron', poste: 'Directrice des opérations', email: 'n.bergeron@perleyrideau.ca', tel: '613-526-7170' },
    ],
    createdAt: '2023-01-12',
    projetsIds: ['p7'],
    soumissionsIds: ['s7', 's13'],
    totalContrats: 750000,
    tauxSucces: 38,
    margemoyenne: 10.5,
  },
  {
    id: 'c7',
    nom: 'Groupe Immobilier Alliance',
    type: 'prive',
    secteur: 'commercial',
    adresse: '3300 rue de la Côte-des-Neiges',
    ville: 'Montréal',
    province: 'QC',
    codePostal: 'H3H 2G9',
    conditionsPaiement: 'Net 30',
    contacts: [
      { nom: 'Éric Lalonde', poste: 'Directeur projets', email: 'e.lalonde@allianceimmo.ca', tel: '514-933-1234' },
    ],
    createdAt: '2022-09-05',
    projetsIds: ['p8'],
    soumissionsIds: ['s14', 's16'],
    totalContrats: 1650000,
    tauxSucces: 45,
    margemoyenne: 15.8,
  },
  {
    id: 'c8',
    nom: 'Cisco Canada',
    type: 'prive',
    secteur: 'industriel',
    adresse: '2323 Yonge St',
    ville: 'Toronto',
    province: 'ON',
    codePostal: 'M4P 2C9',
    conditionsPaiement: 'Net 60',
    contacts: [
      { nom: 'Linda Wong', poste: 'Facilities Manager', email: 'l.wong@cisco.com', tel: '416-922-4000' },
    ],
    createdAt: '2023-04-20',
    projetsIds: [],
    soumissionsIds: ['s17'],
    totalContrats: 0,
    tauxSucces: 0,
    margemoyenne: 0,
  },
  {
    id: 'c9',
    nom: 'Commission scolaire des Portages',
    type: 'public',
    secteur: 'institutionnel',
    adresse: '432 rue MacDonald',
    ville: 'Gatineau',
    province: 'QC',
    codePostal: 'J8L 2T3',
    conditionsPaiement: 'Net 30',
    contacts: [
      { nom: 'François Boucher', poste: 'Directeur bâtiments', email: 'f.boucher@csportages.qc.ca', tel: '819-986-8511' },
    ],
    createdAt: '2021-02-28',
    projetsIds: [],
    soumissionsIds: ['s18', 's19'],
    totalContrats: 420000,
    tauxSucces: 25,
    margemoyenne: 9.2,
  },
  {
    id: 'c10',
    nom: 'Acier Atlas Inc.',
    type: 'prive',
    secteur: 'industriel',
    adresse: '5500 rue Dickson',
    ville: 'Montréal',
    province: 'QC',
    codePostal: 'H1N 2H4',
    conditionsPaiement: 'Net 45',
    contacts: [
      { nom: 'Roberto Ferrante', poste: 'VP Maintenance', email: 'r.ferrante@acieratlas.ca', tel: '514-253-6900' },
    ],
    createdAt: '2022-11-14',
    projetsIds: [],
    soumissionsIds: ['s20'],
    totalContrats: 0,
    tauxSucces: 0,
    margemoyenne: 0,
  },
  {
    id: 'c11',
    nom: 'Ville de Laval',
    type: 'public',
    secteur: 'municipal',
    adresse: '1 Place du Souvenir',
    ville: 'Laval',
    province: 'QC',
    codePostal: 'H7V 1W7',
    conditionsPaiement: 'Net 30',
    contacts: [
      { nom: 'Caroline Lévesque', poste: 'Chef acquisition', email: 'c.levesque@laval.ca', tel: '450-978-8000' },
    ],
    createdAt: '2020-06-01',
    projetsIds: [],
    soumissionsIds: [],
    totalContrats: 5100000,
    tauxSucces: 40,
    margemoyenne: 11.8,
  },
  {
    id: 'c12',
    nom: 'Distribution Couche-Tard',
    type: 'prive',
    secteur: 'commercial',
    adresse: '4204 boul. Industriel',
    ville: 'Laval',
    province: 'QC',
    codePostal: 'H7L 0E3',
    conditionsPaiement: 'Net 30',
    contacts: [
      { nom: 'Claude Archambault', poste: 'Directeur immobilier', email: 'c.archambault@couche-tard.com', tel: '450-662-6632' },
    ],
    createdAt: '2023-02-14',
    projetsIds: [],
    soumissionsIds: [],
    totalContrats: 320000,
    tauxSucces: 67,
    margemoyenne: 18.2,
  },
  {
    id: 'c13',
    nom: 'SNC-Lavalin / AtkinsRealis',
    type: 'prive',
    secteur: 'industriel',
    adresse: '455 René-Lévesque Blvd W',
    ville: 'Montréal',
    province: 'QC',
    codePostal: 'H2Z 1Z3',
    conditionsPaiement: 'Net 60',
    contacts: [
      { nom: 'Isabelle Roy', poste: 'Directrice achats', email: 'i.roy@atkinsrealis.com', tel: '514-393-1000' },
    ],
    createdAt: '2021-10-08',
    projetsIds: [],
    soumissionsIds: [],
    totalContrats: 9800000,
    tauxSucces: 30,
    margemoyenne: 8.9,
  },
  {
    id: 'c14',
    nom: 'MRC des Collines-de-l\'Outaouais',
    type: 'public',
    secteur: 'municipal',
    adresse: '216 rue Principale',
    ville: 'Chelsea',
    province: 'QC',
    codePostal: 'J9B 1L2',
    conditionsPaiement: 'Net 30',
    contacts: [
      { nom: 'Daniel Lacasse', poste: 'Préfet MRC', email: 'd.lacasse@mrccollines.qc.ca', tel: '819-827-0516' },
    ],
    createdAt: '2022-04-22',
    projetsIds: [],
    soumissionsIds: [],
    totalContrats: 680000,
    tauxSucces: 52,
    margemoyenne: 12.5,
  },
  {
    id: 'c15',
    nom: 'Hôpital Montfort',
    type: 'public',
    secteur: 'institutionnel',
    adresse: '713 Montreal Rd',
    ville: 'Ottawa',
    province: 'ON',
    codePostal: 'K1K 0T2',
    conditionsPaiement: 'Net 45',
    contacts: [
      { nom: 'Geneviève Picard', poste: 'Directrice des services techniques', email: 'g.picard@montfort.on.ca', tel: '613-746-4621' },
    ],
    createdAt: '2023-06-30',
    projetsIds: [],
    soumissionsIds: [],
    totalContrats: 1450000,
    tauxSucces: 44,
    margemoyenne: 10.9,
  },
]
