import type { ResultatAO } from '@/types'

export const concurrence: ResultatAO[] = [
  {
    id: 'r1',
    soumissionId: 's1',
    soumissionNumero: 'AO-2024-001',
    titre: 'Réfection infrastructures routières — Aylmer',
    clientNom: 'Ville de Gatineau',
    dateDepot: '2024-02-20',
    resultat: 'gagne',
    prixSoumis: 1850000,
    prixGagnant: 1850000,
    concurrentGagnant: 'Bidexa (nous)',
    rang: 1,
    totalSoumissionnaires: 4,
    ecartPct: 0,
    estimateurNom: 'Jean-Baptiste Côté',
    raisons: ['Prix compétitif', 'Expérience démontrée', 'Plan de travail détaillé'],
  },
  {
    id: 'r2',
    soumissionId: 's2',
    soumissionNumero: 'AO-2024-002',
    titre: 'Agrandissement entrepôt — Phase 2',
    clientNom: 'Construction Gervais & Fils',
    dateDepot: '2024-02-28',
    resultat: 'gagne',
    prixSoumis: 648000,
    prixGagnant: 648000,
    concurrentGagnant: 'Bidexa (nous)',
    rang: 1,
    totalSoumissionnaires: 3,
    ecartPct: 0,
    estimateurNom: 'Sandra Ouellet',
    raisons: ['Relation client établie', 'Délais respectés', 'Prix ajusté'],
  },
  {
    id: 'r3',
    soumissionId: 's4',
    soumissionNumero: 'AO-2024-004',
    titre: 'Remplacement fours industriels — Joliette',
    clientNom: 'Industries Lafarge Canada',
    dateDepot: '2024-02-10',
    resultat: 'perdu',
    prixSoumis: 3150000,
    prixGagnant: 2820000,
    concurrentGagnant: 'Groupe Leduc Industriel',
    rang: 2,
    totalSoumissionnaires: 3,
    ecartPct: -10.5,
    estimateurNom: 'Sandra Ouellet',
    raisons: ['Concurrent plus bas de 10.5%', 'Spécialisation procédés cimentiers concurrents', 'Pas de référence secteur ciment'],
  },
  {
    id: 'r4',
    soumissionId: 's6',
    soumissionNumero: 'AO-2024-006',
    titre: 'Réfection pont — rang du Sauvage',
    clientNom: 'Municipalité de Pontiac',
    dateDepot: '2024-03-20',
    resultat: 'gagne',
    prixSoumis: 387000,
    prixGagnant: 387000,
    concurrentGagnant: 'Bidexa (nous)',
    rang: 1,
    totalSoumissionnaires: 5,
    ecartPct: 0,
    estimateurNom: 'Jean-Baptiste Côté',
    raisons: ['Seul à avoir soumis complet', 'Référence pont similaire'],
  },
  {
    id: 'r5',
    soumissionId: 's9',
    soumissionNumero: 'AO-2024-009',
    titre: 'Installation panneaux solaires — 3 postes HQ',
    clientNom: 'Hydro-Québec',
    dateDepot: '2023-12-15',
    resultat: 'perdu',
    prixSoumis: 1890000,
    prixGagnant: 1610000,
    concurrentGagnant: 'SolairePro Construction',
    rang: 3,
    totalSoumissionnaires: 6,
    ecartPct: -14.8,
    estimateurNom: 'Jean-Baptiste Côté',
    raisons: ['Pas de spécialisation solaire', 'Concurrent spécialisé PV industriel', 'Marge trop haute pour cette niche'],
  },
  {
    id: 'r6',
    soumissionId: 's12',
    soumissionNumero: 'AO-2023-019',
    titre: 'Aqueduc — secteur Masson-Angers',
    clientNom: 'Ville de Gatineau',
    dateDepot: '2023-07-15',
    resultat: 'gagne',
    prixSoumis: 1140000,
    prixGagnant: 1140000,
    concurrentGagnant: 'Bidexa (nous)',
    rang: 1,
    totalSoumissionnaires: 5,
    ecartPct: 0,
    estimateurNom: 'Jean-Baptiste Côté',
    raisons: ['Meilleur prix', 'Expérience aqueduc municipale', 'Délais garantis'],
  },
  {
    id: 'r7',
    soumissionId: 's14',
    soumissionNumero: 'AO-2024-014',
    titre: 'Rénovation tour de bureaux — 12 étages',
    clientNom: 'Groupe Immobilier Alliance',
    dateDepot: '2024-03-01',
    resultat: 'gagne',
    prixSoumis: 1620000,
    prixGagnant: 1620000,
    concurrentGagnant: 'Bidexa (nous)',
    rang: 1,
    totalSoumissionnaires: 4,
    ecartPct: 0,
    estimateurNom: 'Kevin Tran',
    raisons: ['Prix compétitif', 'Présentation qualité supérieure', 'Références commerciales solides'],
  },
  {
    id: 'r8',
    soumissionId: 's18',
    soumissionNumero: 'AO-2023-022',
    titre: 'Réfection gymnase — École St-Joseph',
    clientNom: 'Commission scolaire des Portages',
    dateDepot: '2023-09-30',
    resultat: 'perdu',
    prixSoumis: 218000,
    prixGagnant: 189000,
    concurrentGagnant: 'Rénovations Québec Scolaire',
    rang: 2,
    totalSoumissionnaires: 7,
    ecartPct: -13.3,
    estimateurNom: 'Jean-Baptiste Côté',
    raisons: ['Marché scolaire très compétitif', 'Concurrent volume', 'Coûts MO plus bas chez concurrent'],
  },
  {
    id: 'r9',
    soumissionId: 's3',
    soumissionNumero: 'AO-2024-003',
    titre: 'Maintenance préventive postes HQ — région Outaouais',
    clientNom: 'Hydro-Québec',
    dateDepot: '2024-04-15',
    resultat: 'gagne',
    prixSoumis: 2340000,
    prixGagnant: 2340000,
    concurrentGagnant: 'Bidexa (nous)',
    rang: 1,
    totalSoumissionnaires: 3,
    ecartPct: 0,
    estimateurNom: 'Jean-Baptiste Côté',
    raisons: ['Expérience électrique HT démontrée', 'Équipe certifiée', 'Méthodologie reconnue HQ'],
  },
  {
    id: 'r10',
    soumissionId: 's11',
    soumissionNumero: 'AO-2024-011',
    titre: 'Aménagement parc municipal — Pontiac',
    clientNom: 'Municipalité de Pontiac',
    dateDepot: '2024-04-10',
    resultat: 'gagne',
    prixSoumis: 195000,
    prixGagnant: 195000,
    concurrentGagnant: 'En attente',
    rang: 1,
    totalSoumissionnaires: 4,
    ecartPct: 0,
    estimateurNom: 'Kevin Tran',
    raisons: ['Résultat non encore confirmé'],
  },
  {
    id: 'r11',
    soumissionId: 's16',
    soumissionNumero: 'AO-2024-016',
    titre: 'Aménagement locaux commerciaux — centre Laval',
    clientNom: 'Groupe Immobilier Alliance',
    dateDepot: '2024-04-20',
    resultat: 'gagne',
    prixSoumis: 430000,
    prixGagnant: 430000,
    concurrentGagnant: 'En attente',
    rang: 1,
    totalSoumissionnaires: 3,
    ecartPct: 0,
    estimateurNom: 'Sandra Ouellet',
    raisons: ['Résultat non encore confirmé'],
  },
  {
    id: 'r12',
    soumissionId: 's19',
    soumissionNumero: 'AO-2024-019',
    titre: 'Toiture école primaire Buckingham',
    clientNom: 'Commission scolaire des Portages',
    dateDepot: '2024-04-25',
    resultat: 'gagne',
    prixSoumis: 142000,
    prixGagnant: 142000,
    concurrentGagnant: 'En attente',
    rang: 1,
    totalSoumissionnaires: 5,
    ecartPct: 0,
    estimateurNom: 'Sandra Ouellet',
    raisons: ['Résultat non encore confirmé'],
  },
]
