import type { Fournisseur } from '@/types'

export const fournisseurs: Fournisseur[] = [
  {
    id: 'f1',
    nom: 'Béton Provincial Inc.',
    categorie: 'Béton et granulats',
    adresse: '1280 boul. Industriel, Gatineau QC J8P 7V4',
    ville: 'Gatineau',
    contacts: [
      { nom: 'Daniel Richer', poste: 'Directeur des ventes', email: 'd.richer@betonprovincial.ca', tel: '819-663-4411' },
    ],
    scorePerformance: 88,
    totalAchats: 485000,
    nombreCommandes: 24,
    delaiMoyen: 2,
    createdAt: '2021-03-10',
  },
  {
    id: 'f2',
    nom: 'Aciers de construction Demers',
    categorie: 'Acier et métaux',
    adresse: '3400 rue Industrielle, Laval QC H7L 4Z9',
    ville: 'Laval',
    contacts: [
      { nom: 'Louis Demers', poste: 'Propriétaire', email: 'l.demers@aciersdemers.ca', tel: '450-628-7200' },
    ],
    scorePerformance: 92,
    totalAchats: 312000,
    nombreCommandes: 18,
    delaiMoyen: 5,
    createdAt: '2020-08-15',
  },
  {
    id: 'f3',
    nom: 'Électrique Marchand & Frères',
    categorie: 'Électricité',
    adresse: '820 rue Principale, Hull QC J9A 3L2',
    ville: 'Hull',
    contacts: [
      { nom: 'Vincent Marchand', poste: 'VP opérations', email: 'v.marchand@electricmarchand.ca', tel: '819-777-2233' },
    ],
    scorePerformance: 85,
    totalAchats: 228000,
    nombreCommandes: 12,
    delaiMoyen: 3,
    createdAt: '2021-11-20',
  },
  {
    id: 'f4',
    nom: 'Plomberie Industrielle Savard',
    categorie: 'Plomberie et mécanique',
    adresse: '555 rue Savard, Québec QC G1P 4M5',
    ville: 'Québec',
    contacts: [
      { nom: 'Caroline Savard', poste: 'Directrice générale', email: 'c.savard@plombsavard.ca', tel: '418-686-1122' },
    ],
    scorePerformance: 79,
    totalAchats: 178000,
    nombreCommandes: 9,
    delaiMoyen: 7,
    createdAt: '2022-02-28',
  },
  {
    id: 'f5',
    nom: 'Excavations Fortier',
    categorie: 'Excavation et terrassement',
    adresse: '125 chemin de la Carrière, Pontiac QC J0X 2G0',
    ville: 'Pontiac',
    contacts: [
      { nom: 'Gaétan Fortier', poste: 'Propriétaire', email: 'g.fortier@excavfortier.ca', tel: '819-455-2888' },
    ],
    scorePerformance: 94,
    totalAchats: 395000,
    nombreCommandes: 21,
    delaiMoyen: 1,
    createdAt: '2020-05-01',
  },
  {
    id: 'f6',
    nom: 'Tuyauterie Nord-Est',
    categorie: 'Tuyauterie industrielle',
    adresse: '2800 rue de la Rive, Lachute QC J8H 3W8',
    ville: 'Lachute',
    contacts: [
      { nom: 'Sylvain Perron', poste: 'Directeur technique', email: 's.perron@tuyauteriene.ca', tel: '450-562-7733' },
    ],
    scorePerformance: 81,
    totalAchats: 142000,
    nombreCommandes: 7,
    delaiMoyen: 8,
    createdAt: '2022-09-14',
  },
  {
    id: 'f7',
    nom: 'Menuiserie Pro Carpentier',
    categorie: 'Menuiserie et bois',
    adresse: '440 ave de la Station, Wakefield QC J0X 3G0',
    ville: 'Wakefield',
    contacts: [
      { nom: 'Jean-Guy Carpentier', poste: 'Maître menuisier', email: 'jg.carpentier@menuiseriecarp.ca', tel: '819-459-2200' },
    ],
    scorePerformance: 76,
    totalAchats: 88000,
    nombreCommandes: 6,
    delaiMoyen: 4,
    createdAt: '2023-01-15',
  },
  {
    id: 'f8',
    nom: 'Location Équipements Bouchard',
    categorie: 'Location équipements',
    adresse: '1900 chemin Freeman, Gatineau QC J8Z 1V3',
    ville: 'Gatineau',
    contacts: [
      { nom: 'Denis Bouchard', poste: 'Gestionnaire parc', email: 'd.bouchard@locationbouchard.ca', tel: '819-561-4400' },
    ],
    scorePerformance: 90,
    totalAchats: 267000,
    nombreCommandes: 38,
    delaiMoyen: 1,
    createdAt: '2020-11-01',
  },
  {
    id: 'f9',
    nom: 'Isolation Thermax',
    categorie: 'Isolation et enveloppe',
    adresse: '3100 boul. des Entreprises, Terrebonne QC J6X 4J8',
    ville: 'Terrebonne',
    contacts: [
      { nom: 'Annie Rousseau', poste: 'Représentante commerciale', email: 'a.rousseau@thermax.ca', tel: '450-492-5500' },
    ],
    scorePerformance: 87,
    totalAchats: 156000,
    nombreCommandes: 11,
    delaiMoyen: 4,
    createdAt: '2022-04-20',
  },
  {
    id: 'f10',
    nom: 'Peinture & Revêtements Lafond',
    categorie: 'Peinture et revêtements',
    adresse: '88 rue Lafontaine, Ottawa ON K1L 7W2',
    ville: 'Ottawa',
    contacts: [
      { nom: 'Michel Lafond', poste: 'Directeur projets', email: 'm.lafond@peinturelafond.ca', tel: '613-744-3322' },
    ],
    scorePerformance: 83,
    totalAchats: 94000,
    nombreCommandes: 15,
    delaiMoyen: 2,
    createdAt: '2021-07-08',
  },
  {
    id: 'f11',
    nom: 'Portes & Fenêtres Fenmaster',
    categorie: 'Menuiserie extérieure',
    adresse: '2200 boul. Industriel, Brossard QC J4Y 1L5',
    ville: 'Brossard',
    contacts: [
      { nom: 'Robert Lepage', poste: 'Directeur des ventes', email: 'r.lepage@fenmaster.ca', tel: '450-462-7890' },
    ],
    scorePerformance: 88,
    totalAchats: 112000,
    nombreCommandes: 8,
    delaiMoyen: 10,
    createdAt: '2022-06-30',
  },
  {
    id: 'f12',
    nom: 'Soudures Industrielles Gagné',
    categorie: 'Soudure et métaux ouvrés',
    adresse: '650 rue des Forges, Trois-Rivières QC G8T 5G2',
    ville: 'Trois-Rivières',
    contacts: [
      { nom: 'Simon Gagné', poste: 'Propriétaire', email: 's.gagne@souduresgagne.ca', tel: '819-374-5566' },
    ],
    scorePerformance: 91,
    totalAchats: 204000,
    nombreCommandes: 14,
    delaiMoyen: 6,
    createdAt: '2021-01-22',
  },
]
