import type { Projet } from '@/types'

export const projets: Projet[] = [
  {
    id: 'p1',
    numero: 'PRJ-2024-001',
    titre: 'Réfection infrastructures routières — Aylmer',
    clientId: 'c1',
    clientNom: 'Ville de Gatineau',
    soumissionId: 's1',
    statut: 'en_cours',
    chargeProjNom: 'Martin Beaupré',
    budgetInitial: 1850000,
    budgetActuel: 1850000,
    coutEngages: 1142000,
    avancement: 62,
    dateDebut: '2024-03-01',
    dateFin: '2024-10-31',
    description: 'Réfection complète de 4,2 km de voirie incluant aqueducs et égouts secteur Aylmer.',
    equipe: ['Martin Beaupré', 'Lucie Martel', 'Alex Tremblay', 'Sam Diallo'],
    taches: [
      { id: 't1', titre: 'Signalisation et mobilisation chantier', responsable: 'Alex Tremblay', debut: '2024-03-01', fin: '2024-03-15', avancement: 100, statut: 'termine' },
      { id: 't2', titre: 'Démolition chaussée existante', responsable: 'Lucie Martel', debut: '2024-03-15', fin: '2024-04-30', avancement: 100, statut: 'termine' },
      { id: 't3', titre: 'Travaux réseau aqueduc', responsable: 'Martin Beaupré', debut: '2024-04-01', fin: '2024-06-30', avancement: 85, statut: 'en_cours' },
      { id: 't4', titre: 'Travaux réseau égout', responsable: 'Sam Diallo', debut: '2024-04-15', fin: '2024-07-15', avancement: 70, statut: 'en_cours' },
      { id: 't5', titre: 'Remblayage et structure de chaussée', responsable: 'Lucie Martel', debut: '2024-07-01', fin: '2024-09-15', avancement: 0, statut: 'a_faire' },
      { id: 't6', titre: 'Pose enrobé bitumineux', responsable: 'Alex Tremblay', debut: '2024-09-01', fin: '2024-10-15', avancement: 0, statut: 'a_faire' },
    ],
    ordresChangement: [
      { id: 'oc1', numero: 'OC-001', description: 'Sol contaminé découvert zone A — traitement requis', montant: 42000, statut: 'approuve', date: '2024-04-22' },
      { id: 'oc2', numero: 'OC-002', description: 'Remplacement regard supplémentaire — demande client', montant: 8500, statut: 'en_attente', date: '2024-05-10' },
    ],
    journal: [
      { id: 'j1', date: '2024-03-01', auteur: 'Martin Beaupré', type: 'note', contenu: 'Démarrage officiel du chantier. Équipe complète sur site.' },
      { id: 'j2', date: '2024-04-22', auteur: 'Martin Beaupré', type: 'incident', contenu: 'Sol contaminé découvert en zone A. Arrêt partiel travaux, expert environnement mandaté.' },
      { id: 'j3', date: '2024-04-25', auteur: 'Lucie Martel', type: 'avancement', contenu: 'Démolition complétée à 100%. Début réseau aqueduc confirmé.' },
      { id: 'j4', date: '2024-05-15', auteur: 'Martin Beaupré', type: 'changement', contenu: 'OC-001 approuvé par Ville de Gatineau. Traitement sol en cours.' },
    ],
  },
  {
    id: 'p2',
    numero: 'PRJ-2024-002',
    titre: 'Agrandissement entrepôt — Phase 2',
    clientId: 'c2',
    clientNom: 'Construction Gervais & Fils',
    soumissionId: 's2',
    statut: 'en_cours',
    chargeProjNom: 'Nadia Fontaine',
    budgetInitial: 648000,
    budgetActuel: 648000,
    coutEngages: 285000,
    avancement: 44,
    dateDebut: '2024-04-01',
    dateFin: '2024-08-30',
    description: 'Agrandissement 1200 m² avec dalle, structure acier et enveloppe.',
    equipe: ['Nadia Fontaine', 'Pascal Roy'],
    taches: [
      { id: 't1', titre: 'Fouilles et fondations', responsable: 'Pascal Roy', debut: '2024-04-01', fin: '2024-04-30', avancement: 100, statut: 'termine' },
      { id: 't2', titre: 'Dalle béton', responsable: 'Pascal Roy', debut: '2024-04-20', fin: '2024-05-20', avancement: 100, statut: 'termine' },
      { id: 't3', titre: 'Érection charpente acier', responsable: 'Nadia Fontaine', debut: '2024-05-15', fin: '2024-06-30', avancement: 60, statut: 'en_cours' },
      { id: 't4', titre: 'Enveloppe — murs et toiture', responsable: 'Nadia Fontaine', debut: '2024-06-20', fin: '2024-07-31', avancement: 0, statut: 'a_faire' },
      { id: 't5', titre: 'Portes et finitions', responsable: 'Pascal Roy', debut: '2024-07-15', fin: '2024-08-30', avancement: 0, statut: 'a_faire' },
    ],
    ordresChangement: [],
    journal: [
      { id: 'j1', date: '2024-04-01', auteur: 'Nadia Fontaine', type: 'note', contenu: 'Mobilisation équipe. Préparation terrain terminée.' },
      { id: 'j2', date: '2024-05-20', auteur: 'Nadia Fontaine', type: 'avancement', contenu: 'Dalle complétée. Attente délai cure béton avant érection.' },
    ],
  },
  {
    id: 'p3',
    numero: 'PRJ-2023-012',
    titre: 'Aqueduc — secteur Masson-Angers',
    clientId: 'c1',
    clientNom: 'Ville de Gatineau',
    soumissionId: 's12',
    statut: 'termine',
    chargeProjNom: 'Martin Beaupré',
    budgetInitial: 1140000,
    budgetActuel: 1158000,
    coutEngages: 1102000,
    avancement: 100,
    dateDebut: '2023-08-15',
    dateFin: '2024-01-31',
    description: 'Remplacement réseau aqueduc 3,1 km — DN 300.',
    equipe: ['Martin Beaupré', 'Alex Tremblay'],
    taches: [
      { id: 't1', titre: 'Mobilisation et signalisation', responsable: 'Alex Tremblay', debut: '2023-08-15', fin: '2023-08-31', avancement: 100, statut: 'termine' },
      { id: 't2', titre: 'Tronçon 1 — 1050 ml', responsable: 'Martin Beaupré', debut: '2023-09-01', fin: '2023-10-31', avancement: 100, statut: 'termine' },
      { id: 't3', titre: 'Tronçon 2 — 1050 ml', responsable: 'Martin Beaupré', debut: '2023-10-15', fin: '2023-12-15', avancement: 100, statut: 'termine' },
      { id: 't4', titre: 'Tronçon 3 — 1000 ml', responsable: 'Alex Tremblay', debut: '2023-11-15', fin: '2024-01-15', avancement: 100, statut: 'termine' },
    ],
    ordresChangement: [
      { id: 'oc1', numero: 'OC-001', description: 'Roc imprévu — explosif requis tronçon 2', montant: 18000, statut: 'approuve', date: '2023-10-20' },
    ],
    journal: [
      { id: 'j1', date: '2024-01-31', auteur: 'Martin Beaupré', type: 'note', contenu: 'Projet complété. Mise en service réseau confirmée par client.' },
    ],
  },
  {
    id: 'p4',
    numero: 'PRJ-2024-004',
    titre: 'Maintenance préventive postes électriques HQ',
    clientId: 'c3',
    clientNom: 'Hydro-Québec',
    soumissionId: 's3',
    statut: 'en_cours',
    chargeProjNom: 'Émilie Caron',
    budgetInitial: 2340000,
    budgetActuel: 2340000,
    coutEngages: 195000,
    avancement: 8,
    dateDebut: '2024-05-01',
    dateFin: '2027-04-30',
    description: 'Contrat 3 ans de maintenance préventive sur 22 postes de distribution Outaouais.',
    equipe: ['Émilie Caron', 'Félix Beaumont', 'Tony Nguyen'],
    taches: [
      { id: 't1', titre: 'Inspection initiale — 22 postes', responsable: 'Félix Beaumont', debut: '2024-05-01', fin: '2024-07-31', avancement: 30, statut: 'en_cours' },
      { id: 't2', titre: 'Maintenance préventive — Année 1', responsable: 'Émilie Caron', debut: '2024-08-01', fin: '2025-04-30', avancement: 0, statut: 'a_faire' },
    ],
    ordresChangement: [],
    journal: [
      { id: 'j1', date: '2024-05-01', auteur: 'Émilie Caron', type: 'note', contenu: 'Début du contrat. Réunion de démarrage avec HQ.' },
    ],
  },
  {
    id: 'p5',
    numero: 'PRJ-2024-005',
    titre: 'Rénovation tour de bureaux — 12 étages',
    clientId: 'c7',
    clientNom: 'Groupe Immobilier Alliance',
    soumissionId: 's14',
    statut: 'planification',
    chargeProjNom: 'Nadia Fontaine',
    budgetInitial: 1620000,
    budgetActuel: 1620000,
    coutEngages: 48000,
    avancement: 3,
    dateDebut: '2024-06-01',
    dateFin: '2025-03-31',
    description: 'Rénovation espaces communs + 48 bureaux clé en main.',
    equipe: ['Nadia Fontaine', 'Pascal Roy', 'Marie-Claude Pion'],
    taches: [
      { id: 't1', titre: 'Plans et devis finaux', responsable: 'Nadia Fontaine', debut: '2024-06-01', fin: '2024-07-15', avancement: 15, statut: 'en_cours' },
      { id: 't2', titre: 'Appel d\'offres sous-traitants', responsable: 'Pascal Roy', debut: '2024-07-15', fin: '2024-08-15', avancement: 0, statut: 'a_faire' },
      { id: 't3', titre: 'Démolition sélective', responsable: 'Marie-Claude Pion', debut: '2024-08-01', fin: '2024-09-30', avancement: 0, statut: 'a_faire' },
    ],
    ordresChangement: [],
    journal: [
      { id: 'j1', date: '2024-06-01', auteur: 'Nadia Fontaine', type: 'note', contenu: 'Réunion de démarrage. Revue des plans avec client.' },
    ],
  },
  {
    id: 'p6',
    numero: 'PRJ-2024-006',
    titre: 'Réfection pont — rang du Sauvage',
    clientId: 'c5',
    clientNom: 'Municipalité de Pontiac',
    soumissionId: 's6',
    statut: 'en_cours',
    chargeProjNom: 'Martin Beaupré',
    budgetInitial: 387000,
    budgetActuel: 387000,
    coutEngages: 201000,
    avancement: 52,
    dateDebut: '2024-04-15',
    dateFin: '2024-08-15',
    description: 'Remplacement tablier de pont sur 22 m de portée.',
    equipe: ['Martin Beaupré', 'Sam Diallo'],
    taches: [
      { id: 't1', titre: 'Démontage tablier existant', responsable: 'Sam Diallo', debut: '2024-04-15', fin: '2024-05-15', avancement: 100, statut: 'termine' },
      { id: 't2', titre: 'Réparation culées', responsable: 'Martin Beaupré', debut: '2024-05-01', fin: '2024-06-15', avancement: 80, statut: 'en_cours' },
      { id: 't3', titre: 'Installation nouveau tablier', responsable: 'Sam Diallo', debut: '2024-06-01', fin: '2024-07-31', avancement: 0, statut: 'a_faire' },
      { id: 't4', titre: 'Garde-fous et signalisation', responsable: 'Martin Beaupré', debut: '2024-07-15', fin: '2024-08-15', avancement: 0, statut: 'a_faire' },
    ],
    ordresChangement: [],
    journal: [
      { id: 'j1', date: '2024-04-15', auteur: 'Martin Beaupré', type: 'note', contenu: 'Fermeture du pont confirmée. Signalisation déviation en place.' },
    ],
  },
  {
    id: 'p7',
    numero: 'PRJ-2024-007',
    titre: 'Réfection toiture — aile B, CHSLD Perley',
    clientId: 'c6',
    clientNom: 'CHSLD Perley-Rideau',
    soumissionId: 's7',
    statut: 'planification',
    chargeProjNom: 'Émilie Caron',
    budgetInitial: 285000,
    budgetActuel: 285000,
    coutEngages: 12000,
    avancement: 4,
    dateDebut: '2024-06-15',
    dateFin: '2024-09-30',
    description: 'Remplacement membrane EPDM 3200 m² + isolation.',
    equipe: ['Émilie Caron'],
    taches: [
      { id: 't1', titre: 'Préparation et installation échafaudages', responsable: 'Émilie Caron', debut: '2024-06-15', fin: '2024-06-30', avancement: 0, statut: 'a_faire' },
      { id: 't2', titre: 'Démolition membrane existante', responsable: 'Émilie Caron', debut: '2024-07-01', fin: '2024-07-31', avancement: 0, statut: 'a_faire' },
      { id: 't3', titre: 'Pose isolation et membrane EPDM', responsable: 'Émilie Caron', debut: '2024-07-15', fin: '2024-09-15', avancement: 0, statut: 'a_faire' },
    ],
    ordresChangement: [],
    journal: [],
  },
  {
    id: 'p8',
    numero: 'PRJ-2024-008',
    titre: 'Aménagement locaux commerciaux — centre Laval',
    clientId: 'c7',
    clientNom: 'Groupe Immobilier Alliance',
    soumissionId: 's16',
    statut: 'planification',
    chargeProjNom: 'Nadia Fontaine',
    budgetInitial: 430000,
    budgetActuel: 430000,
    coutEngages: 0,
    avancement: 0,
    dateDebut: '2024-07-01',
    dateFin: '2024-11-30',
    description: 'Aménagement 12 cellules commerciales — gros-oeuvre et finitions.',
    equipe: ['Nadia Fontaine', 'Marie-Claude Pion'],
    taches: [
      { id: 't1', titre: 'Estimation finale et appel sous-traitants', responsable: 'Nadia Fontaine', debut: '2024-07-01', fin: '2024-07-31', avancement: 0, statut: 'a_faire' },
    ],
    ordresChangement: [],
    journal: [],
  },
]
