import type { Soumission } from '@/types'

export const soumissions: Soumission[] = [
  {
    id: 's1',
    numero: 'AO-2024-001',
    titre: 'Réfection des infrastructures routières — secteur Aylmer',
    clientId: 'c1',
    clientNom: 'Ville de Gatineau',
    type: 'appel_offre_public',
    statut: 'gagnee',
    estimateurId: 'u1',
    estimateurNom: 'Jean-Baptiste Côté',
    dateReception: '2024-01-15',
    dateDepot: '2024-02-20',
    prixSoumis: 1850000,
    marge: 11.5,
    version: 3,
    description: 'Réfection complète de 4,2 km de voirie incluant aqueducs et égouts.',
    documents: [
      { id: 'd1', nom: 'Plans et devis.pdf', type: 'plan', moduleRef: 'soumission', moduleId: 's1', version: '1.0', taille: '8.4 MB', createdAt: '2024-01-16', uploadePar: 'Jean-Baptiste Côté' },
      { id: 'd2', nom: 'Addenda #1.pdf', type: 'addenda', moduleRef: 'soumission', moduleId: 's1', version: '1.0', taille: '1.2 MB', createdAt: '2024-02-01', uploadePar: 'Marie-Josée Langlois' },
    ],
    checklist: [
      { id: 'ck1', label: 'Documents reçus et classés', done: true },
      { id: 'ck2', label: 'Addenda vérifiés', done: true },
      { id: 'ck3', label: 'Estimation complétée', done: true },
      { id: 'ck4', label: 'Approbation direction', done: true },
      { id: 'ck5', label: 'Formulaire de soumission signé', done: true },
      { id: 'ck6', label: 'Cautionnement inclus', done: true },
    ],
    createdAt: '2024-01-15',
  },
  {
    id: 's2',
    numero: 'AO-2024-002',
    titre: 'Agrandissement entrepôt — Phase 2',
    clientId: 'c2',
    clientNom: 'Construction Gervais & Fils',
    type: 'soumission_directe',
    statut: 'gagnee',
    estimateurId: 'u2',
    estimateurNom: 'Sandra Ouellet',
    dateReception: '2024-02-01',
    dateDepot: '2024-02-28',
    prixSoumis: 648000,
    marge: 14.2,
    version: 2,
    description: 'Agrandissement 1200 m² avec dalle, structure acier et enveloppe.',
    documents: [
      { id: 'd3', nom: 'Devis technique.pdf', type: 'plan', moduleRef: 'soumission', moduleId: 's2', version: '2.0', taille: '3.1 MB', createdAt: '2024-02-02', uploadePar: 'Marc Gervais' },
    ],
    checklist: [
      { id: 'ck1', label: 'Documents reçus et classés', done: true },
      { id: 'ck2', label: 'Addenda vérifiés', done: true },
      { id: 'ck3', label: 'Estimation complétée', done: true },
      { id: 'ck4', label: 'Approbation direction', done: true },
      { id: 'ck5', label: 'Formulaire signé', done: true },
      { id: 'ck6', label: 'Cautionnement inclus', done: false },
    ],
    createdAt: '2024-02-01',
  },
  {
    id: 's3',
    numero: 'AO-2024-003',
    titre: 'Maintenance préventive postes électriques — région Outaouais',
    clientId: 'c3',
    clientNom: 'Hydro-Québec',
    type: 'appel_offre_public',
    statut: 'deposee',
    estimateurId: 'u1',
    estimateurNom: 'Jean-Baptiste Côté',
    dateReception: '2024-03-10',
    dateDepot: '2024-04-15',
    prixSoumis: 2340000,
    marge: 9.8,
    version: 1,
    description: 'Contrat 3 ans de maintenance préventive sur 22 postes de distribution.',
    documents: [
      { id: 'd4', nom: 'Cahier des charges.pdf', type: 'plan', moduleRef: 'soumission', moduleId: 's3', version: '1.0', taille: '12.7 MB', createdAt: '2024-03-11', uploadePar: 'Sophie Tremblay' },
    ],
    checklist: [
      { id: 'ck1', label: 'Documents reçus et classés', done: true },
      { id: 'ck2', label: 'Addenda vérifiés', done: true },
      { id: 'ck3', label: 'Estimation complétée', done: true },
      { id: 'ck4', label: 'Approbation direction', done: false },
      { id: 'ck5', label: 'Formulaire signé', done: false },
      { id: 'ck6', label: 'Cautionnement inclus', done: false },
    ],
    createdAt: '2024-03-10',
  },
  {
    id: 's4',
    numero: 'AO-2024-004',
    titre: 'Remplacement fours industriels — usine Joliette',
    clientId: 'c4',
    clientNom: 'Industries Lafarge Canada',
    type: 'demande_de_prix',
    statut: 'perdue',
    estimateurId: 'u2',
    estimateurNom: 'Sandra Ouellet',
    dateReception: '2024-01-20',
    dateDepot: '2024-02-10',
    prixSoumis: 3150000,
    marge: 12.0,
    version: 2,
    description: 'Remplacement de 3 fours rotatifs et installation de nouveaux brûleurs.',
    documents: [],
    checklist: [
      { id: 'ck1', label: 'Documents reçus', done: true },
      { id: 'ck2', label: 'Estimation complétée', done: true },
      { id: 'ck3', label: 'Soumission déposée', done: true },
      { id: 'ck4', label: 'Résultat reçu', done: true },
      { id: 'ck5', label: 'Analyse post-mortem', done: true },
      { id: 'ck6', label: 'Cautionnement', done: false },
    ],
    createdAt: '2024-01-20',
  },
  {
    id: 's5',
    numero: 'AO-2024-005',
    titre: 'Rénovation centre communautaire — secteur Hull',
    clientId: 'c1',
    clientNom: 'Ville de Gatineau',
    type: 'appel_offre_public',
    statut: 'en_preparation',
    estimateurId: 'u3',
    estimateurNom: 'Kevin Tran',
    dateReception: '2024-04-01',
    dateDepot: '2024-05-15',
    prixSoumis: 0,
    marge: 0,
    version: 1,
    description: 'Rénovation complète du centre communautaire Lucien-Cannon — 2800 m².',
    documents: [
      { id: 'd5', nom: 'Plans architecturaux.pdf', type: 'plan', moduleRef: 'soumission', moduleId: 's5', version: '1.0', taille: '22.4 MB', createdAt: '2024-04-02', uploadePar: 'Jean-Baptiste Côté' },
    ],
    checklist: [
      { id: 'ck1', label: 'Documents reçus et classés', done: true },
      { id: 'ck2', label: 'Addenda vérifiés', done: false },
      { id: 'ck3', label: 'Estimation complétée', done: false },
      { id: 'ck4', label: 'Approbation direction', done: false },
      { id: 'ck5', label: 'Formulaire signé', done: false },
      { id: 'ck6', label: 'Cautionnement inclus', done: false },
    ],
    createdAt: '2024-04-01',
  },
  {
    id: 's6',
    numero: 'AO-2024-006',
    titre: 'Réfection pont — rang du Sauvage',
    clientId: 'c5',
    clientNom: 'Municipalité de Pontiac',
    type: 'appel_offre_public',
    statut: 'gagnee',
    estimateurId: 'u1',
    estimateurNom: 'Jean-Baptiste Côté',
    dateReception: '2024-02-14',
    dateDepot: '2024-03-20',
    prixSoumis: 387000,
    marge: 13.5,
    version: 1,
    description: 'Remplacement tablier de pont sur 22 m de portée.',
    documents: [],
    checklist: [
      { id: 'ck1', label: 'Documents reçus', done: true },
      { id: 'ck2', label: 'Estimation complétée', done: true },
      { id: 'ck3', label: 'Approbation direction', done: true },
      { id: 'ck4', label: 'Formulaire signé', done: true },
      { id: 'ck5', label: 'Cautionnement inclus', done: true },
      { id: 'ck6', label: 'Résultat reçu', done: true },
    ],
    createdAt: '2024-02-14',
  },
  {
    id: 's7',
    numero: 'AO-2024-007',
    titre: 'Réfection toiture — aile B',
    clientId: 'c6',
    clientNom: 'CHSLD Perley-Rideau',
    type: 'soumission_directe',
    statut: 'en_validation',
    estimateurId: 'u2',
    estimateurNom: 'Sandra Ouellet',
    dateReception: '2024-04-05',
    dateDepot: '2024-05-01',
    prixSoumis: 285000,
    marge: 10.5,
    version: 2,
    description: 'Remplacement membrane EPDM 3200 m² + isolation en jeu.',
    documents: [],
    checklist: [
      { id: 'ck1', label: 'Documents reçus', done: true },
      { id: 'ck2', label: 'Estimation complétée', done: true },
      { id: 'ck3', label: 'Approbation direction', done: false },
      { id: 'ck4', label: 'Formulaire signé', done: false },
      { id: 'ck5', label: 'Cautionnement inclus', done: false },
      { id: 'ck6', label: 'Résultat reçu', done: false },
    ],
    createdAt: '2024-04-05',
  },
  {
    id: 's8',
    numero: 'AO-2024-008',
    titre: 'Construction bureaux administratifs',
    clientId: 'c2',
    clientNom: 'Construction Gervais & Fils',
    type: 'soumission_directe',
    statut: 'brouillon',
    estimateurId: 'u3',
    estimateurNom: 'Kevin Tran',
    dateReception: '2024-04-18',
    dateDepot: '2024-06-01',
    prixSoumis: 0,
    marge: 0,
    version: 1,
    description: 'Construction 800 m² bureaux sur 2 étages — clé en main.',
    documents: [],
    checklist: [
      { id: 'ck1', label: 'Documents reçus', done: false },
      { id: 'ck2', label: 'Estimation complétée', done: false },
      { id: 'ck3', label: 'Approbation direction', done: false },
      { id: 'ck4', label: 'Formulaire signé', done: false },
      { id: 'ck5', label: 'Cautionnement inclus', done: false },
      { id: 'ck6', label: 'Résultat reçu', done: false },
    ],
    createdAt: '2024-04-18',
  },
  {
    id: 's9',
    numero: 'AO-2024-009',
    titre: 'Installation panneaux solaires — 3 postes',
    clientId: 'c3',
    clientNom: 'Hydro-Québec',
    type: 'appel_offre_public',
    statut: 'perdue',
    estimateurId: 'u1',
    estimateurNom: 'Jean-Baptiste Côté',
    dateReception: '2023-11-01',
    dateDepot: '2023-12-15',
    prixSoumis: 1890000,
    marge: 10.2,
    version: 1,
    description: 'Installation systèmes solaires PV sur 3 postes de transformation.',
    documents: [],
    checklist: [
      { id: 'ck1', label: 'Documents reçus', done: true },
      { id: 'ck2', label: 'Estimation complétée', done: true },
      { id: 'ck3', label: 'Approbation direction', done: true },
      { id: 'ck4', label: 'Formulaire signé', done: true },
      { id: 'ck5', label: 'Cautionnement inclus', done: true },
      { id: 'ck6', label: 'Résultat reçu', done: true },
    ],
    createdAt: '2023-11-01',
  },
  {
    id: 's10',
    numero: 'AO-2024-010',
    titre: 'Modernisation broyeurs — ligne de production 4',
    clientId: 'c4',
    clientNom: 'Industries Lafarge Canada',
    type: 'demande_de_prix',
    statut: 'en_preparation',
    estimateurId: 'u2',
    estimateurNom: 'Sandra Ouellet',
    dateReception: '2024-04-10',
    dateDepot: '2024-05-30',
    prixSoumis: 0,
    marge: 0,
    version: 1,
    description: 'Remplacement 2 broyeurs à boulets + API de contrôle.',
    documents: [],
    checklist: [
      { id: 'ck1', label: 'Documents reçus', done: true },
      { id: 'ck2', label: 'Estimation en cours', done: false },
      { id: 'ck3', label: 'Approbation direction', done: false },
      { id: 'ck4', label: 'Formulaire signé', done: false },
      { id: 'ck5', label: 'Cautionnement inclus', done: false },
      { id: 'ck6', label: 'Résultat reçu', done: false },
    ],
    createdAt: '2024-04-10',
  },
  {
    id: 's11',
    numero: 'AO-2024-011',
    titre: 'Aménagement parc municipal — terrain naturel',
    clientId: 'c5',
    clientNom: 'Municipalité de Pontiac',
    type: 'appel_offre_public',
    statut: 'deposee',
    estimateurId: 'u3',
    estimateurNom: 'Kevin Tran',
    dateReception: '2024-03-01',
    dateDepot: '2024-04-10',
    prixSoumis: 195000,
    marge: 14.8,
    version: 1,
    description: 'Aménagement parc 5 ha incluant sentiers, mobilier et éclairage.',
    documents: [],
    checklist: [
      { id: 'ck1', label: 'Documents reçus', done: true },
      { id: 'ck2', label: 'Estimation complétée', done: true },
      { id: 'ck3', label: 'Approbation direction', done: true },
      { id: 'ck4', label: 'Formulaire signé', done: true },
      { id: 'ck5', label: 'Cautionnement inclus', done: true },
      { id: 'ck6', label: 'Résultat reçu', done: false },
    ],
    createdAt: '2024-03-01',
  },
  {
    id: 's12',
    numero: 'AO-2023-019',
    titre: 'Aqueduc — secteur Masson-Angers',
    clientId: 'c1',
    clientNom: 'Ville de Gatineau',
    type: 'appel_offre_public',
    statut: 'gagnee',
    estimateurId: 'u1',
    estimateurNom: 'Jean-Baptiste Côté',
    dateReception: '2023-06-01',
    dateDepot: '2023-07-15',
    prixSoumis: 1140000,
    marge: 10.8,
    version: 2,
    description: 'Remplacement réseau aqueduc 3,1 km — DN 300.',
    documents: [],
    checklist: [
      { id: 'ck1', label: 'Complet', done: true },
      { id: 'ck2', label: 'Complet', done: true },
      { id: 'ck3', label: 'Complet', done: true },
      { id: 'ck4', label: 'Complet', done: true },
      { id: 'ck5', label: 'Complet', done: true },
      { id: 'ck6', label: 'Complet', done: true },
    ],
    createdAt: '2023-06-01',
  },
  {
    id: 's13',
    numero: 'AO-2024-013',
    titre: 'Mise aux normes CVC — aile gériatrique',
    clientId: 'c6',
    clientNom: 'CHSLD Perley-Rideau',
    type: 'appel_offre_prive',
    statut: 'annulee',
    estimateurId: 'u2',
    estimateurNom: 'Sandra Ouellet',
    dateReception: '2024-01-10',
    dateDepot: '2024-02-28',
    prixSoumis: 0,
    marge: 0,
    version: 1,
    description: 'Remplacement système CVC — budget annulé par client.',
    documents: [],
    checklist: [
      { id: 'ck1', label: 'Documents reçus', done: true },
      { id: 'ck2', label: 'Estimation partielle', done: false },
      { id: 'ck3', label: 'Approbation direction', done: false },
      { id: 'ck4', label: 'Formulaire signé', done: false },
      { id: 'ck5', label: 'Cautionnement inclus', done: false },
      { id: 'ck6', label: 'Résultat reçu', done: false },
    ],
    createdAt: '2024-01-10',
  },
  {
    id: 's14',
    numero: 'AO-2024-014',
    titre: 'Rénovation tour de bureaux — 12 étages',
    clientId: 'c7',
    clientNom: 'Groupe Immobilier Alliance',
    type: 'soumission_directe',
    statut: 'gagnee',
    estimateurId: 'u3',
    estimateurNom: 'Kevin Tran',
    dateReception: '2024-01-28',
    dateDepot: '2024-03-01',
    prixSoumis: 1620000,
    marge: 16.2,
    version: 3,
    description: 'Rénovation espaces communs + 48 bureaux clé en main.',
    documents: [],
    checklist: [
      { id: 'ck1', label: 'Complet', done: true },
      { id: 'ck2', label: 'Complet', done: true },
      { id: 'ck3', label: 'Complet', done: true },
      { id: 'ck4', label: 'Complet', done: true },
      { id: 'ck5', label: 'Complet', done: true },
      { id: 'ck6', label: 'Complet', done: true },
    ],
    createdAt: '2024-01-28',
  },
  {
    id: 's15',
    numero: 'AO-2024-015',
    titre: 'Construction poste de transformation 315 kV',
    clientId: 'c3',
    clientNom: 'Hydro-Québec',
    type: 'appel_offre_public',
    statut: 'en_preparation',
    estimateurId: 'u1',
    estimateurNom: 'Jean-Baptiste Côté',
    dateReception: '2024-04-20',
    dateDepot: '2024-06-30',
    prixSoumis: 0,
    marge: 0,
    version: 1,
    description: 'Construction neuf d\'un poste HT 315/25 kV — 60 MVA.',
    documents: [],
    checklist: [
      { id: 'ck1', label: 'Documents reçus', done: true },
      { id: 'ck2', label: 'Estimation en cours', done: false },
      { id: 'ck3', label: 'Approbation direction', done: false },
      { id: 'ck4', label: 'Formulaire signé', done: false },
      { id: 'ck5', label: 'Cautionnement inclus', done: false },
      { id: 'ck6', label: 'Résultat reçu', done: false },
    ],
    createdAt: '2024-04-20',
  },
  {
    id: 's16',
    numero: 'AO-2024-016',
    titre: 'Aménagement locaux commerciaux — centre Laval',
    clientId: 'c7',
    clientNom: 'Groupe Immobilier Alliance',
    type: 'soumission_directe',
    statut: 'deposee',
    estimateurId: 'u2',
    estimateurNom: 'Sandra Ouellet',
    dateReception: '2024-03-15',
    dateDepot: '2024-04-20',
    prixSoumis: 430000,
    marge: 15.5,
    version: 1,
    description: 'Aménagement 12 cellules commerciales — gros-oeuvre et finitions.',
    documents: [],
    checklist: [
      { id: 'ck1', label: 'Documents reçus', done: true },
      { id: 'ck2', label: 'Estimation complétée', done: true },
      { id: 'ck3', label: 'Approbation direction', done: true },
      { id: 'ck4', label: 'Formulaire signé', done: true },
      { id: 'ck5', label: 'Cautionnement inclus', done: true },
      { id: 'ck6', label: 'Résultat en attente', done: false },
    ],
    createdAt: '2024-03-15',
  },
  {
    id: 's17',
    numero: 'AO-2024-017',
    titre: 'Data Center — infrastructure mécanique',
    clientId: 'c8',
    clientNom: 'Cisco Canada',
    type: 'appel_offre_prive',
    statut: 'en_preparation',
    estimateurId: 'u3',
    estimateurNom: 'Kevin Tran',
    dateReception: '2024-04-22',
    dateDepot: '2024-06-15',
    prixSoumis: 0,
    marge: 0,
    version: 1,
    description: 'Infrastructure HVAC et plomberie pour nouveau data center 2000 m².',
    documents: [],
    checklist: [
      { id: 'ck1', label: 'Documents reçus', done: true },
      { id: 'ck2', label: 'Estimation en cours', done: false },
      { id: 'ck3', label: 'Approbation direction', done: false },
      { id: 'ck4', label: 'Formulaire signé', done: false },
      { id: 'ck5', label: 'Cautionnement inclus', done: false },
      { id: 'ck6', label: 'Résultat reçu', done: false },
    ],
    createdAt: '2024-04-22',
  },
  {
    id: 's18',
    numero: 'AO-2023-022',
    titre: 'Réfection gymnase — École St-Joseph',
    clientId: 'c9',
    clientNom: 'Commission scolaire des Portages',
    type: 'appel_offre_public',
    statut: 'perdue',
    estimateurId: 'u1',
    estimateurNom: 'Jean-Baptiste Côté',
    dateReception: '2023-08-15',
    dateDepot: '2023-09-30',
    prixSoumis: 218000,
    marge: 9.5,
    version: 1,
    description: 'Réfection plancher, murs et éclairage gymnase 800 m².',
    documents: [],
    checklist: [
      { id: 'ck1', label: 'Complet', done: true },
      { id: 'ck2', label: 'Complet', done: true },
      { id: 'ck3', label: 'Complet', done: true },
      { id: 'ck4', label: 'Complet', done: true },
      { id: 'ck5', label: 'Complet', done: true },
      { id: 'ck6', label: 'Complet', done: true },
    ],
    createdAt: '2023-08-15',
  },
  {
    id: 's19',
    numero: 'AO-2024-019',
    titre: 'Toiture école primaire Buckingham',
    clientId: 'c9',
    clientNom: 'Commission scolaire des Portages',
    type: 'appel_offre_public',
    statut: 'deposee',
    estimateurId: 'u2',
    estimateurNom: 'Sandra Ouellet',
    dateReception: '2024-03-20',
    dateDepot: '2024-04-25',
    prixSoumis: 142000,
    marge: 11.2,
    version: 1,
    description: 'Remplacement toiture plate EPDM 1400 m² + descentes pluviales.',
    documents: [],
    checklist: [
      { id: 'ck1', label: 'Documents reçus', done: true },
      { id: 'ck2', label: 'Estimation complétée', done: true },
      { id: 'ck3', label: 'Approbation direction', done: true },
      { id: 'ck4', label: 'Formulaire signé', done: true },
      { id: 'ck5', label: 'Cautionnement inclus', done: true },
      { id: 'ck6', label: 'Résultat en attente', done: false },
    ],
    createdAt: '2024-03-20',
  },
  {
    id: 's20',
    numero: 'AO-2024-020',
    titre: 'Remplacement pont roulant 50T',
    clientId: 'c10',
    clientNom: 'Acier Atlas Inc.',
    type: 'demande_de_prix',
    statut: 'brouillon',
    estimateurId: 'u3',
    estimateurNom: 'Kevin Tran',
    dateReception: '2024-04-25',
    dateDepot: '2024-06-01',
    prixSoumis: 0,
    marge: 0,
    version: 1,
    description: 'Fourniture et installation pont roulant bipoitrelle 50T — portée 28m.',
    documents: [],
    checklist: [
      { id: 'ck1', label: 'Documents reçus', done: false },
      { id: 'ck2', label: 'Estimation en cours', done: false },
      { id: 'ck3', label: 'Approbation direction', done: false },
      { id: 'ck4', label: 'Formulaire signé', done: false },
      { id: 'ck5', label: 'Cautionnement inclus', done: false },
      { id: 'ck6', label: 'Résultat reçu', done: false },
    ],
    createdAt: '2024-04-25',
  },
]
